name: Compile Action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: cleanup old pdfs
        run: "git rm  --ignore-unmatch *.pdf"
      - name: Run latexmk
      - name: Run LaTeX action on main.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          texlive_version: 2025
      - name: Run LaTeX action on plates.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: plates.tex
          latexmk_use_lualatex: true
          texlive_version: 2025
      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: change file name (main.pdf)
        run: "mv main.pdf main$BUILD_TIME.pdf"
      - name: change file name (plates.pdf)
        run: "mv plates.pdf plates$BUILD_TIME.pdf"  
      - name: add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.pdf'
