name: Compile Action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2025-historic
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: add permissions
        run: "git config --global --add safe.directory /__w/zenaphorisms/zenaphorisms"
      - name: cleanup old pdfs
        run: "git rm  --ignore-unmatch *.pdf"
      - name: Run latexmk
        run: "latexmk --pdflatex main.tex"
      - name: Run latexmk
        run: "latexmk --lualatex plates.tex"
      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: change file name
        run: "mv main.pdf main$BUILD_TIME.pdf"
      - name: change file name
        run: "mv plates.pdf plates$BUILD_TIME.pdf"  
      - name: add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.pdf'

